hakoot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quiz.urls"))
]

quiz/urls.py
from django.urls import path
from . import views

app_name = "quiz"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile/<str:username>", views.index, name="profile"),
    path("view/<int:quiz_id>", views.view, name="view"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("edit/<int:quiz_id>", views.edit, name="edit"),
    path("delete/<int:quiz_id>", views.delete, name="delete"),
    path("play/<int:quiz_id>", views.play, name="play"),
    path("play/score/<int:quiz_id>", views.score, name="score"),
]

quiz/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class User(AbstractUser):
    pass


class Quiz(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="quizzes")
    name = models.CharField(max_length=128)
    desc = models.CharField(max_length=512, default="")
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def num_questions(self):
        return self.questions.all().count()


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions")
    question = models.CharField(max_length=512)
    qn_no = models.IntegerField(default=1, validators=[
        MinValueValidator(0)
    ])
    correct_option = models.IntegerField(default=0, choices=(
        (i - 1, i) for i in range(1, 5)
    ))
    time_limit = models.IntegerField(default=30, choices=(
        (i * 10, i * 10) for i in range(1, 7)
    ))


class Option(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="options")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="options")
    qn_no = models.IntegerField(default=1, validators=[
        MinValueValidator(0)
    ])
    option = models.CharField(max_length=512)
    option_no = models.IntegerField(default=1)


class Quiz_attempt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="attempts")
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="attempts")
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def score(self):
        return sum([attempt.score() for attempt in self.qn_attempts.all()])
    
    def current_question(self):
        return self.qn_attempts.count()
    
class Question_attempt(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="attempts")
    option_chosen = models.IntegerField(default=-1)
    quiz_attempt = models.ForeignKey(Quiz_attempt, on_delete=models.CASCADE, related_name="qn_attempts")
    time_left = models.DecimalField(decimal_places=2, max_digits=10, default=0.0)

    def correct(self):
        return int(self.question.correct_option) == int(self.option_chosen)
    
    def score(self):
        if self.correct():
            return int(500 + 500 * (self.time_left / self.question.time_limit))
        else:
            return 0

quiz/forms.py
from django import forms
from .models import *

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question', 'correct_option', 'time_limit', 'qn_no']
        labels = {
            "time_limit": "Time Limit (s)"
        }
        widgets = {
            "qn_no": forms.HiddenInput()
        }


class OptionForm(forms.ModelForm):
    class Meta:
        model = Option
        fields = ['option', 'qn_no']
        labels = {
            "option": ""
        }
        widgets = {
            "qn_no": forms.HiddenInput()
        }

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'desc']
        widgets = {
            "desc": forms.Textarea(attrs={'rows': 3})
        }

quiz/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
import json

from .models import *
from .forms import *
from .util import *

def index(request, username=None):
    """
    Handles the index page view for quizzes.

    Parameters:
    - request: The HTTP request object.
    - username (optional): The username of the quiz creator.

    Returns:
    - The rendered HTML response for the index page.

    Description:
    This function handles the rendering of the index page for quizzes. 
    It accepts an HTTP request object and an optional username parameter. 
    If a username is provided, the page title is set to the username, and only quizzes created by that user are displayed. 
    If no username is provided, the page title is set to "All Quizzes" and all quizzes are displayed.
    If the request method is POST, the page title is set to "Search Results" and the quizzes are filtered based on a search query provided in the request POST data.
    The function then calls the `get_page` function to paginate the quizzes and retrieve the current page. 
    Finally, it renders the `index.html` template with the page title and page object passed as context.
    """
    if username:
        page_title = username
        quizzes = Quiz.objects.filter(creator__username=username)
    else:
        page_title = "All Quizzes"
        quizzes = Quiz.objects.all()
    if request.method == "POST":
        page_title = "Search Results"
        query = str(request.POST['query']).lower()
        quizzes = quizzes.filter(name__contains=query)
    page = get_page(request, quizzes.order_by("-timestamp"))
    return render(request, "quiz/index.html", {
            "page_title": page_title,
            "page": page
        })

def view(request, quiz_id):
    """
    Renders the view for a specific quiz.

    Args:
        request (HttpRequest): The HTTP request object.
        quiz_id (int): The ID of the quiz.

    Returns:
        HttpResponse: The rendered view of the quiz.
    """
    quiz = Quiz.objects.get(id=quiz_id)
    if request.user.is_authenticated:
        quiz_attempt = Quiz_attempt.objects.filter(user=request.user, quiz=quiz).first()
    else:
        quiz_attempt = None

    all_attempts = Quiz_attempt.objects.filter(quiz=quiz).all()
    leaderboard = sorted(all_attempts, key=lambda x: x.score(), reverse=True)[:5]

    return render(request, "quiz/view.html", {
        "quiz": quiz,
        "quiz_attempt": quiz_attempt,
        "leaderboard": leaderboard

    })

@login_required
def play(request, quiz_id):
    """
    Takes a request and a quiz_id and performs the necessary actions to play a quiz.
    
    Parameters:
    - request: The request object containing information about the user and the request method.
    - quiz_id: The ID of the quiz to be played.
    
    Returns:
    - If the request method is "GET", renders the "quiz/play.html" template with the following context:
        - "quiz": The Quiz object corresponding to the quiz_id.
        - "quiz_attempt": The Quiz_attempt object created or retrieved for the current user and quiz.
        - "qns": The queryset of questions for the quiz, excluding those that the user has attempted, ordered by question number.
        - "options": The queryset of options for the quiz, ordered by question number and option number.
    - If the request method is "PUT", saves the user's chosen option and time left for the current question and returns a JsonResponse with the following data:
        - "correct_option": The correct option for the current question.
        - "score": The score calculated for the current question attempt.
    """
    quiz = Quiz.objects.get(id=quiz_id)
    quiz_attempt, created_new = Quiz_attempt.objects.get_or_create(
        user=request.user,
        quiz=quiz
    )
    if request.method == "GET":
        qn_attempts = quiz_attempt.qn_attempts.all().order_by("question__qn_no")
        return render(request, "quiz/play.html", {
            "quiz": quiz,
            "quiz_attempt": quiz_attempt,
            "qns": quiz.questions.exclude(attempts__in=qn_attempts).all().order_by("qn_no"),
            "options": quiz.options.all().order_by("qn_no", "option_no"),
        })
    elif request.method == "PUT":
        data = json.loads(request.body)
        time_left = int(data["time_left"])
        option_chosen = int(data["option_chosen"])
        qn = quiz.questions.get(qn_no=quiz_attempt.current_question())
        qn_attempt, created_new = Question_attempt.objects.get_or_create(
            question=qn,
            quiz_attempt=quiz_attempt
        )
        qn_attempt.option_chosen = option_chosen
        qn_attempt.time_left = time_left
        qn_attempt.save()
        return JsonResponse({
            "correct_option": qn.correct_option,
            "score": qn_attempt.score()
            })

@login_required
def score(request, quiz_id):
    """
    Get the score for a quiz attempt.

    Parameters:
    - request: The HTTP request object.
    - quiz_id: The ID of the quiz.

    Returns:
    - A JSON response containing the score of the quiz attempt.
    """
    quiz = Quiz.objects.get(id=quiz_id)
    quiz_attempt = Quiz_attempt.objects.get(
        user=request.user,
        quiz=quiz
    )
    all_attempts = Quiz_attempt.objects.filter(quiz=quiz).all()
    top_scores = sorted(all_attempts, key=lambda x: x.score(), reverse=True)[:5]
    return JsonResponse({
        "in_leaderboard": quiz_attempt in top_scores,
        "username": quiz_attempt.user.username,
        "score": quiz_attempt.score(),
        "leaderboard": [{
            "username": attempt.user.username,
            "score": attempt.score()
        } for attempt in top_scores]
    })

def login_view(request):
    """
    Logs in a user.

    Parameters:
    - request: The HTTP request object.

    Returns:
    - HttpResponseRedirect: If the user is successfully logged in, it redirects to the "quiz:index" page.
    - HttpResponse: If the login is unsuccessful, it renders the "quiz/login.html" template with an error message.
    """
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("quiz:index"))
        else:
            return render(request, "quiz/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "quiz/login.html")


def logout_view(request):
    """
    Logs out the user who made the request.
    
    Parameters:
        request (HttpRequest): The request object representing the current HTTP request.
        
    Returns:
        HttpResponseRedirect: A redirect response to the index page of the quiz app.
    """
    logout(request)
    return HttpResponseRedirect(reverse("quiz:index"))


def register(request):
    """
    Registers a new user.

    Parameters:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "quiz/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "quiz/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("quiz:index"))
    else:
        return render(request, "quiz/register.html")
    

@login_required    
def create(request):
    """
    Creates a new quiz.

    Parameters:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponseRedirect: A redirect response to the "my_quizzes" page if the quiz creation is successful.
        HttpResponse: A rendered HTML response with the "create.html" template and the necessary context variables if the quiz creation is not successful.
    """
    qn_formset = modelformset_factory(Question, form=QuestionForm, extra=0)
    option_formset = modelformset_factory(Option, form=OptionForm, extra=0)

    if request.method == 'POST':
        quiz_form = QuizForm(request.POST)
        qn_forms = qn_formset(request.POST, prefix="question")
        option_forms = option_formset(request.POST, prefix="option")
        print(request.POST)
    else:
        quiz_form = QuizForm()
        qn_forms = qn_formset(queryset=Question.objects.none(), prefix="question")
        option_forms = option_formset(queryset=Option.objects.none(), prefix="option")

    if all([quiz_form.is_valid(), qn_forms.is_valid(), option_forms.is_valid()]):
        save_forms(request, quiz_form, qn_forms, option_forms)
        return HttpResponseRedirect(reverse("quiz:profile", args=[request.user.username]))
    
    else:
        [print(form.errors) for form in [quiz_form, qn_forms, option_forms] if form.errors]
    
    return render(request, "quiz/create.html", {
        "page_title": "New Quiz",
        "quiz_form": quiz_form,
        "qn_forms": qn_forms,

quiz/templates/quiz/create.html
{% extends "quiz/layout.html" %}
{% load static %}

{% block body %}
    <h2 class="mt-3 ml-3">{{ page_title }}</h2>
    {% if page_title == "Edit Quiz" %}
        {% url 'quiz:edit' as url %}
    {% else %}
        {% url 'quiz:create' as url %}
    {% endif %}
    <form id="form" action="{{ url }}" method="post" class="ml-4 mb-3">
        <div id="csrf_token" style="display: none;">{{ csrf_token }}</div>
        {% csrf_token %}
        <!-- quiz title -->
        <div class="form-group">
            {{ quiz_form.as_p }}
            <hr class="mt-3 mb-3">
        </div>
        
        <div id="questions">
            {{ qn_forms.management_form }}
            {{ option_forms.management_form }}
            <!-- load questions -->
            {% for qn_form in qn_forms %}
                <div class="form-group qn">
                    <h3 class="font-weight-bold qn_no">Question {{ forloop.counter }}:</h3>
                    <div class="qn_form">{{ qn_form.as_div }}</div>
                    <!-- load options -->
                    <h5>Options:</h5>
                    <ol>
                        {% for option_form in option_forms %}
                            {% if option_form.qn_no.value == qn_form.qn_no.value %}
                                <li class="option mt-1">
                                    {{ option_form.as_div }}
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ol>
                    <button class="remove_qn btn btn-danger mt-2" type="button">Remove Question</button>
                    <hr class="mt-3 mb-3">
                </div>
            {% endfor %}
        </div>
        <button id="add_question" type="button" class="btn btn-primary">Add Question</button>
        <button id="submit" type="submit" class="btn btn-success">Save Quiz</button>
    </form>
    {% if page_title == "Edit Quiz" %}
        <form id="del_quiz" action="{% url 'quiz:delete' quiz_id %}" method="post">
            {% csrf_token %}
            <button id="del" type="submit" class="btn btn-danger ml-4 mb-3">Delete Quiz</button>
        </form>
    {% endif %}


    <!-- template for new question -->
    <div id="new_qn" class="form-group qn" style="display: none;">
        <h3 class="font-weight-bold qn_no"></h3>
        <div class="qn_form">{{ qn_forms.empty_form.as_div }}</div>
        <h5>Options:</h5>
        <ol>
            {% for i in '1234'|make_list %}
                <li class="option mt-1">
                    {{ option_forms.empty_form.as_div }}
                </li>
            {% endfor %}
        </ol>
        <button class="remove_qn btn btn-danger mt-2" type="button">Remove Question</button>
        <hr class="mt-3 mb-3">
    </div>   

{% endblock %}

{% block script %}
    <script src="{% static 'quiz/create.js' %}"></script>
{% endblock %}

quiz/templates/quiz/index.html
{% extends "quiz/layout.html" %}
{% load static %}

{% block body %}
    <h2 class="m-3">{{ page_title }}</h2>
    {% if page_title != "Search Results" %}
        <div class="d-flex">
            <form method="post" class="form-inline mx-3 justify-content-left" action="{% url 'quiz:index' %}">
                {% csrf_token %}
                <input class="form-control mr-2" type="search" name="query" placeholder="Search Quizzes" required>
                <button class="btn btn-success" type="submit">Search</button>
            </form>    
        </div>
    {% endif %}

    {% for quiz in page %}
        <div class="card m-3">
            <div class="card-body">
                {% if quiz.creator == user %}
                    {% url 'quiz:edit' quiz.id as url %}
                {% else %}
                    {% url 'quiz:view' quiz.id as url %}
                {% endif %}
                <a href="{{ url }}">
                    <h3 class="card-title text-dark">{{ quiz.name }}</h3>
                </a>
                <div class="card-text">
                    <div>{{ quiz.num_questions }} questions</div>
                    <a href="{% url 'quiz:profile' quiz.creator %}">
                        <div class="text-muted">{{ quiz.creator }}</div>
                    </a>    
                </div>
            </div>
        </div>
    {% empty %}
        <h3 class="m-3">No quizzes found.</h3>
    {% endfor %}
    <!-- pagination -->
    <p class="text-muted d-flex justify-content-center mt-3">Page {{ page.number }} of {{ page.paginator.num_pages }}</p>
    <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
                {% endif %}
                {% if page.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>    
    </div>
{% endblock %}

quiz/templates/quiz/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}HaKoot!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'quiz/styles.css' %}" rel="stylesheet">
        <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
        {% block script %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'quiz:index' %}">HaKoot!</a>
            <div>
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quiz:profile' request.user.username %}"><strong>{{ user.username }}</strong></a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quiz:create' %}">Make Quiz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quiz:logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quiz:login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'quiz:register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

quiz/templates/quiz/login.html
{% extends "quiz/layout.html" %}

{% block body %}

    <h2 class="m-3">Login</h2>

    {% if message %}
        <div class="mx-3 text-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'quiz:login' %}" method="post" class="m-3">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            <input class="form-control mt-1 mb-3" type="password" name="password" placeholder="Password">
            <input class="btn btn-primary" type="submit" value="Login">
        </div>
    </form>

    <div class="m-3">
        Don't have an account? <a href="{% url 'quiz:register' %}">Register here.</a>
    </div>

{% endblock %}

quiz/templates/quiz/play.html
{% extends "quiz/layout.html" %}
{% load static %}

{% block body %}
    <div id="quiz_info" data-csrf_token="{{ csrf_token }}" data-quiz_id="{{ quiz.id }}" data-curr_qn="{{ quiz_attempt.current_question }}" data-num_qns="{{ quiz.num_questions }}" data-time_left="{{ quiz_attempt.time_left }}"></div>
    <div class="d-flex m-3">
        <h1 id="title">{{ quiz.name }}</h1>
        <button id="curr_qn" class="ml-auto btn btn-dark">{{ quiz_attempt.current_question|add:1 }}/{{ quiz.num_questions }}</button>
    </div>
    {% for qn in qns %}
        <div id="qn_{{ qn.qn_no }}" data-time_limit="{{ qn.time_limit }}" class="card m-3 qn" style="display: none;">
            <h2 class="card-header">{{ qn.question }}</h2>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="timer">
                        <div class="row justify-content-center">
                            <h3 class="card-text row time_left mb-3"></h3>
                        </div>
                        <div class="progress mx-auto mb-2" style="max-width: 300px;">
                            <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div> 
                        <div class="row justify-content-center text-secondary">
                            <div>500p</div>
                            <div style="width: 270px;"></div>
                            <div>1000p</div>
                        </div>
                    </div>
                    <div class="results row justify-content-center" style="display: none;">
                        <h1 class="symbol card-text text-light text-center rounded-circle mb-2" style="height: 50px; width: 50px;"></h1>
                        <div class="w-100"></div>
                        <h3 class="result card-text mb-2"></h3>
                        <div class="w-100"></div>
                        <h5 class="score card-text mb-2"></h5>        
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        {% for option in options %}
                            {% if option.qn_no == qn.qn_no %}
                                <button class="btn m-1 col option" type="button" data-option_no="{{ option.option_no }}" data-qn_no="{{ option.qn_no }}" style="color: white;">
                                    <strong>{{ option.option }}</strong>
                                </button>
                                {% if forloop.counter|divisibleby:2 %}
                                    <div class="w-100"></div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}        
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}

    <div class="card m-3" id="leaderboard" style="display: none;">
        <div class="card-header row justify-content-center">
            <h3 class="card-title">Leaderboard</h3>
        </div>
        <ul class="list-group list-group-flush"></ul>
    </div>

    <button id="next" class="btn btn-primary mx-3" type="button" style="display: none;">Next</button>
    <a id="finish" href="{% url 'quiz:view' quiz.id %}" style="display: none;">
        <button class="btn btn-success mx-3" type="button">Finish</button>
    </a>

{% endblock %}

{% block script %}
    <script src="{% static 'quiz/play.js' %}"></script>
{% endblock %}

quiz/templates/quiz/register.html
{% extends "quiz/layout.html" %}

{% block body %}

    <h2 class="m-3">Register</h2>

    {% if message %}
        <div class="mx-3 text-danger">{{ message }}</div>
    {% endif %}

    <form action="{% url 'quiz:register' %}" method="post" class="m-3">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            <input class="form-control my-1" type="email" name="email" placeholder="Email Address">
            <input class="form-control" type="password" name="password" placeholder="Password">
            <input class="form-control mt-1 mb-3" type="password" name="confirmation" placeholder="Confirm Password">
            <input class="btn btn-primary" type="submit" value="Register">
        </div>
    </form>

    <div class="m-3">
        Already have an account? <a href="{% url 'quiz:login' %}">Log In here.</a>
    </div>

{% endblock %}

quiz/templates/quiz/view.html
{% extends "quiz/layout.html" %}
{% load static %}

{% block body %}
    <div class="card m-3">
        <h1 class="card-header">{{ quiz.name }}</h1>
        <div class="card-body">
            <a href="{% url 'quiz:profile' quiz.creator %}">
                <h5 class="card-title text-dark">{{ quiz.creator }}</h5>   
            </a>
            <h6 class="card-text">{{ quiz.num_questions }} Questions</h6>
            <p class="card-text">{{ quiz.desc }}</p>
            {% if user.is_authenticated and quiz_attempt is None %}
                <a href="{% url 'quiz:play' quiz.id %}"><button class="btn btn-success">Play!</button></a>
            {% elif user.is_authenticated %}
                <button class="btn btn-success" disabled>Already Attempted</button>
            {% else %}
                <button class="btn btn-success" disabled>Login to Play</button>
            {% endif %}
        </div>    
        <div class="card-footer text-muted">{{ quiz.timestamp }}</div>        
    </div>
    <div class="card m-3" id="leaderboard">
        <div class="card-header row justify-content-center">
            <h3 class="card-title">Leaderboard</h3>
        </div>
        <ul class="list-group list-group-flush">
            {% for quiz_attempt in leaderboard %}
                {% if quiz_attempt.user == user %}
                    <li class="list-group-item list-group-item-success">
                {% else %}
                    <li class="list-group-item">
                {% endif %}
                        <div class="row">
                            <div class="col-1">{{ forloop.counter }}</div>
                            <div class="col-9 username">{{ quiz_attempt.user.username }}</div>
                            <div class="col-2 score">{{ quiz_attempt.score }}</div>
                        </div>
                    </li>
            {% empty %}
                <li class="list-group-item">No attempts yet</li>
            {% endfor %}    
            {% if quiz_attempt not in leaderboard and quiz_attempt is not None %}
                <li class="list-group-item list-group-item-success">
                    <div class="row">
                        <div class="col-1"></div>
                        <div class="col-9 username">{{ quiz_attempt.user.username }}</div>
                        <div class="col-2 score">{{ quiz_attempt.score }}</div>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
{% endblock %}